infra.datasource.username = swift
infra.datasource.password = swift
infra.datasource.driverClassName = net.sf.log4jdbc.sql.jdbcapi.DriverSpy
infra.datasource.url = jdbc:log4jdbc:mariadb://localhost:3306/swift_ticket?autoReconnect=true&amp;allowMultiQueries=true&amp;sessionVariables=wait_timeout=600&amp;zeroDateTimeBehavior=convertToNull


